"""
Énumérations pour les types de distorsion, schémas de couleurs et formes.
"""

from enum import Enum


class DistortionType(Enum):
    """Types de distorsion disponibles"""
    RANDOM = "random"
    SINE = "sine" 
    PERLIN = "perlin"
    CIRCULAR = "circular"
    SWIRL = "swirl"
    RIPPLE = "ripple"
    FLOW = "flow"
    PULSE = "pulse"
    CHECKERBOARD = "checkerboard"
    CHECKERBOARD_DIAGONAL = "checkerboard_diagonal"
    TORNADO = "tornado"
    SPIRAL = "spiral"
    SHEAR = "shear"
    LENS = "lens"
    SPIRAL_WAVE = "spiral_wave"
    NOISE_ROTATION = "noise_rotation"
    CURL_WARP = "curl_warp"
    FRACTAL_NOISE = "fractal_noise"
    MOIRE = "moire"
    KALEIDOSCOPE_TWIST = "kaleidoscope_twist"


class ColorScheme(Enum):
    """Schémas de couleurs disponibles"""
    MONOCHROME = "monochrome"
    BLACK_WHITE_RADIAL = "black_white_radial"
    BLACK_WHITE_ALTERNATING = "black_white_alternating"
    GRADIENT = "gradient"
    RAINBOW = "rainbow"
    COMPLEMENTARY = "complementary"
    # TEMPERATURE = "temperature"
    PASTEL = "pastel"
    NEON = "neon"
    # OCEAN = "ocean"
    # FIRE = "fire"
    # FOREST = "forest"
    ANALOGUOUS = "analogous"
    CYBERPUNK = "cyberpunk"
    AURORA_BOREALIS = "aurora_borealis"
    INFRARED_THERMAL = "infrared_thermal"
    DUOTONE_ACCENT = "duotone_accent"
    DESERT = "desert"
    METALLICS = "metallics"
    REGGAE = "reggae"
    SUNSET = "sunset"


class ShapeType(Enum):
    """Types de formes disponibles"""
    SQUARE = "square"
    CIRCLE = "circle"
    TRIANGLE = "triangle"
    HEXAGON = "hexagon"
    STAR = "star"
    PENTAGON = "pentagon"
    DIAMOND = "diamond"
    KOCH_SNOWFLAKE = "koch_snowflake"